.localvar 0 arguments
.localvar 1 len 185
.localvar 2 i 186
.localvar 3 objID 187

:[0]
pushi.e 0
pushi.e -5
pushi.e 0
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 1
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 2
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 3
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 4
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 5
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 6
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 7
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 8
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 9
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 10
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 11
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 12
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 13
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 14
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 15
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 16
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 17
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 18
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 19
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 20
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 21
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 22
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 23
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 24
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 25
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 26
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 27
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 28
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 29
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 30
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 31
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 32
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 33
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 34
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 35
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 36
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 37
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 38
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 39
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 40
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 41
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 42
pop.v.i [array]global.__objectDepths
pushi.e 0
pushi.e -5
pushi.e 43
pop.v.i [array]global.__objectDepths
push.s "choicebox"@204
pushi.e -5
pushi.e 0
pop.v.s [array]global.__objectNames
push.s "gameobj"@206
pushi.e -5
pushi.e 1
pop.v.s [array]global.__objectNames
push.s "openobj"@207
pushi.e -5
pushi.e 2
pop.v.s [array]global.__objectNames
push.s "txtbox"@208
pushi.e -5
pushi.e 3
pop.v.s [array]global.__objectNames
push.s "curtains"@209
pushi.e -5
pushi.e 4
pop.v.s [array]global.__objectNames
push.s "blackscrn"@210
pushi.e -5
pushi.e 5
pop.v.s [array]global.__objectNames
push.s "inventory"@211
pushi.e -5
pushi.e 6
pop.v.s [array]global.__objectNames
push.s "scenemanager"@212
pushi.e -5
pushi.e 7
pop.v.s [array]global.__objectNames
push.s "incidentmanager"@213
pushi.e -5
pushi.e 8
pop.v.s [array]global.__objectNames
push.s "statdisplay"@214
pushi.e -5
pushi.e 9
pop.v.s [array]global.__objectNames
push.s "namebox"@215
pushi.e -5
pushi.e 10
pop.v.s [array]global.__objectNames
push.s "text_tester"@216
pushi.e -5
pushi.e 11
pop.v.s [array]global.__objectNames
push.s "body"@217
pushi.e -5
pushi.e 12
pop.v.s [array]global.__objectNames
push.s "test_settings"@218
pushi.e -5
pushi.e 13
pop.v.s [array]global.__objectNames
push.s "scene_tester"@219
pushi.e -5
pushi.e 14
pop.v.s [array]global.__objectNames
push.s "splashscreens"@220
pushi.e -5
pushi.e 15
pop.v.s [array]global.__objectNames
push.s "home_manager"@221
pushi.e -5
pushi.e 16
pop.v.s [array]global.__objectNames
push.s "br_manager"@222
pushi.e -5
pushi.e 17
pop.v.s [array]global.__objectNames
push.s "office_manager"@223
pushi.e -5
pushi.e 18
pop.v.s [array]global.__objectNames
push.s "start_manager"@224
pushi.e -5
pushi.e 19
pop.v.s [array]global.__objectNames
push.s "boss_manager"@225
pushi.e -5
pushi.e 20
pop.v.s [array]global.__objectNames
push.s "GO_manager"@226
pushi.e -5
pushi.e 21
pop.v.s [array]global.__objectNames
push.s "TEMPLATEMANAGER"@227
pushi.e -5
pushi.e 22
pop.v.s [array]global.__objectNames
push.s "chloe_manager"@228
pushi.e -5
pushi.e 23
pop.v.s [array]global.__objectNames
push.s "polly_manager"@229
pushi.e -5
pushi.e 24
pop.v.s [array]global.__objectNames
push.s "vic_manager"@230
pushi.e -5
pushi.e 25
pop.v.s [array]global.__objectNames
push.s "erika_manager"@231
pushi.e -5
pushi.e 26
pop.v.s [array]global.__objectNames
push.s "stacy_manager"@232
pushi.e -5
pushi.e 27
pop.v.s [array]global.__objectNames
push.s "pearl_manager"@233
pushi.e -5
pushi.e 28
pop.v.s [array]global.__objectNames
push.s "jesse_manager"@234
pushi.e -5
pushi.e 29
pop.v.s [array]global.__objectNames
push.s "kathy_manager"@235
pushi.e -5
pushi.e 30
pop.v.s [array]global.__objectNames
push.s "vend_manager"@236
pushi.e -5
pushi.e 31
pop.v.s [array]global.__objectNames
push.s "game_manager"@237
pushi.e -5
pushi.e 32
pop.v.s [array]global.__objectNames
push.s "vendmachine"@238
pushi.e -5
pushi.e 33
pop.v.s [array]global.__objectNames
push.s "bubble"@239
pushi.e -5
pushi.e 34
pop.v.s [array]global.__objectNames
push.s "convey"@240
pushi.e -5
pushi.e 35
pop.v.s [array]global.__objectNames
push.s "food"@241
pushi.e -5
pushi.e 36
pop.v.s [array]global.__objectNames
push.s "game_body"@242
pushi.e -5
pushi.e 37
pop.v.s [array]global.__objectNames
push.s "leftbutt"@243
pushi.e -5
pushi.e 38
pop.v.s [array]global.__objectNames
push.s "rightbutt"@244
pushi.e -5
pushi.e 39
pop.v.s [array]global.__objectNames
push.s "table_1"@245
pushi.e -5
pushi.e 40
pop.v.s [array]global.__objectNames
push.s "table_2"@246
pushi.e -5
pushi.e 41
pop.v.s [array]global.__objectNames
push.s "jonhead"@247
pushi.e -5
pushi.e 42
pop.v.s [array]global.__objectNames
push.s "boss_body"@248
pushi.e -5
pushi.e 43
pop.v.s [array]global.__objectNames
pushglb.v global.__objectDepths
call.i array_length_1d(argc=1)
pop.v.v local.len
call.i @@NewGMLArray@@(argc=0)
pop.v.v global.__objectID2Depth
pushi.e 0
pop.v.i local.i

:[1]
pushloc.v local.i
pushloc.v local.len
cmp.v.v LT
bf [end]

:[2]
pushi.e -5
pushloc.v local.i
conv.v.i
push.v [array]global.__objectNames
call.i asset_get_index(argc=1)
pop.v.v local.objID
pushloc.v local.objID
pushi.e 0
cmp.i.v GTE
bf [4]

:[3]
pushi.e -5
pushloc.v local.i
conv.v.i
push.v [array]global.__objectDepths
pushi.e -5
pushloc.v local.objID
conv.v.i
pop.v.v [array]global.__objectID2Depth

:[4]
push.v local.i
push.e 1
add.i.v
pop.v.v local.i
b [1]

:[end]